# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tliz2p3QWbDdM0iJuG8fYp7z0zXhqT-k
"""

class Horse:
    def __init__(self, name= 'Mike', breed='American Walking Pony', age=4, speed=25):
        self.name = name
        self.breed = breed
        self.age = age
        self.speed = speed
    def display_info(self):
        #Displays the horse's details
        print(f"Horse Name: {self.name}")
        print(f"Breed: {self.breed}")
        print(f"Age: {self.age} years")
        print(f"Speed: {self.speed} km/h")

    def run(self):
        #Simulates the horse running.
        print(f"{self.name} is running at {self.speed} km/h!")


def main():
    """
    Main function to create and test Horse objects.
    """
    horses = []
    n = int(input("Enter the number of horses: "))

    for i in range(n):
        print(f"\nEnter details for Horse {i+1}:")
        name = input("Enter Name: ")
        breed = input("Enter Breed: ")
        age = int(input("Enter Age: "))
        speed = float(input("Enter Speed (km/h): "))

        horse = Horse(name, breed, age, speed)
        horses.append(horse)

    print("\nHorse Details:")
    for horse in horses:
        horse.display_info()
        horse.run()
        print("---------------------------")

if __name__ == "__main__":
    main()